# Generated by Django 2.1 on 2018-08-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
        migrations.RemoveField(
            model_name='job',
            name='summary',
        ),
        migrations.AddField(
            model_name='job',
            name='details',
            field=models.TextField(default='placeholder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='placeholder', max_length=100),
            preserve_default=False,
        ),
    ]
