# Generated by Django 2.1 on 2018-08-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180815_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.CharField(default='http://example.com', max_length=100),
            preserve_default=False,
        ),
    ]
